In [1]:
import requests
from bs4 import BeautifulSoup

In [2]:
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36'}
response = requests.get("https://www.zomato.com/bangalore/box8-desi-meals-indiranagar-bangalore/order",headers=headers)

In [3]:
content = response.content
soup = BeautifulSoup(content,"html.parser")

In [4]:
import os
import json
import pandas as pd

In [5]:
data1=[]
data2=[]
data3=[]
data4=[]
data5=[]
data6=[]
data7=[]
data8=[]

In [6]:
containers = soup.find_all("div",{"class":"sc-1s0saks-10 cYSFTJ"})

In [9]:
from bs4.element import Tag
for container in containers:
  item_name = container.find('h4',attrs={'class':'sc-1s0saks-15 iSmBPS'})
  #print(item_name.text)
  data1.append(item_name.text)

  item_price = container.find('span',attrs={'class':'sc-17hyc2s-1 cCiQWA'})
  #print(item_price.text)
  data2.append(item_price.text)

  item_rating = container.find('div',attrs={'class':'sc-z30xqq-3 bewuUV'})
  #print(item_rating.text)
  if item_rating is not None:
    rating = item_rating.text
  else:
    rating = None
  data3.append(rating)

  noof_rating = container.find('span',attrs={'class':'sc-z30xqq-4 hTgtKb'})
  #print(noof_rating.text)
  if noof_rating is not None:
    noofrating = noof_rating.text
  else:
    noofrating = None
  data4.append(noofrating)

  item_desc = container.find('p',attrs={'class':'sc-1s0saks-12 hcROsL'})
  #print(item_desc.text)
  if item_desc is not None:
    desc = item_desc.text
  else:
    desc = None
  data5.append(desc)

  best_tag = container.find('div',attrs={'class':'sc-2gamf4-0 hILTXF'})
  #print(best_tag.text)
  if best_tag is not None:
    tag = best_tag.text
  else:
    tag = None
  data6.append(tag)

In [10]:
for res_name in soup.find_all('h1',attrs={'class':'sc-7kepeu-0 sc-kafWEX kTxZkY'}):
  print(res_name.text)
  data7.append(res_name.text)

BOX8 - Desi Meals

In [11]:
for res_area in soup.find_all('a',attrs={'href':'https://www.zomato.com/bangalore/indiranagar-restaurants','class':"sc-cmTdod fjhUCy"}):
  print(res_area.text)
  data8.append(res_area.text)

Indiranagar, Bangalore

In [12]:
q = {'Restaurant Name':data7,'Restaurant Area':data8,'Item name':data1,'Item price':data2,'Rating':data3,'No of Rating':data4,'Item description':data5,'Bestseller tag':data6}

In [13]:
df = pd.DataFrame.from_dict(q, orient='index')
df = df.transpose()

In [14]:
df.head(50)

      Restaurant Name  ... Bestseller tag
0   BOX8 - Desi Meals  ...       MUST TRY
1   BOX8 - Desi Meals  ...           None
2                None  ...       MUST TRY
3                None  ...       MUST TRY
4                None  ...           None
5                None  ...           None
6                None  ...           None
7                None  ...       MUST TRY
8                None  ...           None
9                None  ...           None
10               None  ...       MUST TRY
11               None  ...           None
12               None  ...           None
13               None  ...           None
14               None  ...           None
15               None  ...           None
16               None  ...           None
17               None  ...           None
18               None  ...           None
19               None  ...           None
20               None  ...           None
21               None  ...           None
22               None  ...       MUST TRY
23               None  ...           None
24               None  ...           None
25               None  ...       MUST TRY
26               None  ...           None
27               None  ...           None
28               None  ...           None
29               None  ...           None
30               None  ...       MUST TRY
31               None  ...       MUST TRY
32               None  ...       MUST TRY
33               None  ...           None
34               None  ...           None
35               None  ...           None
36               None  ...           None
37               None  ...           None
38               None  ...           None
39               None  ...           None
40               None  ...           None
41               None  ...           None
42               None  ...           None
43               None  ...           None
44               None  ...           None
45               None  ...           None
46               None  ...           None
47               None  ...           None
48               None  ...           None
49               None  ...           None

[50 rows x 8 columns]

In [15]:
df.tail()

    Restaurant Name  ... Bestseller tag
345            None  ...           None
346            None  ...           None
347            None  ...           None
348            None  ...           None
349            None  ...           None

[5 rows x 8 columns]

In [16]:
df['Restaurant Name'].fillna(value='BOX8 - Desi Meals',inplace=True)
df.head()

     Restaurant Name  ... Bestseller tag
0  BOX8 - Desi Meals  ...       MUST TRY
1  BOX8 - Desi Meals  ...           None
2  BOX8 - Desi Meals  ...       MUST TRY
3  BOX8 - Desi Meals  ...       MUST TRY
4  BOX8 - Desi Meals  ...           None

[5 rows x 8 columns]

In [17]:
df['Restaurant Area'].fillna(value='Indiranagar,Bangalore',inplace=True)
df.head()

     Restaurant Name  ... Bestseller tag
0  BOX8 - Desi Meals  ...       MUST TRY
1  BOX8 - Desi Meals  ...           None
2  BOX8 - Desi Meals  ...       MUST TRY
3  BOX8 - Desi Meals  ...       MUST TRY
4  BOX8 - Desi Meals  ...           None

[5 rows x 8 columns]

In [18]:
df.to_csv('Restaurant 3.csv')

In [19]:
df.isnull().sum()

Restaurant Name       0
Restaurant Area       0
Item name             0
Item price            0
Rating               18
No of Rating         18
Item description      0
Bestseller tag      330
dtype: int64

In [20]:
df.shape

(350, 8)